-- Database: 'cse 340 project', public schema
-- Assignment 2, Task 2

-- Create client_type data type
DROP TYPE IF EXISTS public.account_type;
CREATE TYPE public.account_type AS ENUM (
    'Client',
    'Employee',
    'Admin'
);

-- Table structure for table 'classification'
CREATE TABLE IF NOT EXISTS public.classification (
    classification_id INT GENERATED BY DEFAULT AS IDENTITY,
    classification_name CHARACTER VARYING NOT NULL,
    CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);

-- Table structure for table 'inventory'
CREATE TABLE IF NOT EXISTS public.inventory (
    inv_id INT GENERATED BY DEFAULT AS IDENTITY,
    inv_make VARCHAR(50) NOT NULL,
    inv_model VARCHAR(50) NOT NULL,
    inv_year INTEGER NOT NULL,
    inv_description TEXT NOT NULL,
    inv_image VARCHAR(255) NOT NULL,
    inv_thumbnail VARCHAR(255) NOT NULL,
    inv_price DECIMAL(10,2) NOT NULL,
    inv_miles INTEGER NOT NULL,
    inv_color VARCHAR(50) NOT NULL,
    classification_id INTEGER NOT NULL,
    CONSTRAINT inventory_pk PRIMARY KEY (inv_id),
    CONSTRAINT fk_classification FOREIGN KEY (classification_id)
        REFERENCES public.classification (classification_id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE NO ACTION
);

-- Table structure for table 'account'
CREATE TABLE IF NOT EXISTS public.account (
    account_id INT GENERATED BY DEFAULT AS IDENTITY,
    account_firstname VARCHAR(50) NOT NULL,
    account_lastname VARCHAR(50) NOT NULL,
    account_email VARCHAR(100) NOT NULL UNIQUE,
    account_password VARCHAR(100) NOT NULL,
    account_type account_type NOT NULL DEFAULT 'Client',
    CONSTRAINT account_pk PRIMARY KEY (account_id)
);

-- Insert initial classification data
INSERT INTO public.classification (classification_name) VALUES
('Sport'),
('SUV'),
('Sedan'),
('Truck'),
('Van');

-- Insert initial inventory data
INSERT INTO public.inventory (inv_make, inv_model, inv_year, inv_description, inv_image, inv_thumbnail, inv_price, inv_miles, inv_color, classification_id) VALUES
('Jeep', 'Wrangler', 2018, 'The Jeep Wrangler is a compact and mid-size four-wheel drive off-road SUV.', '/images/vehicles/jeep-wrangler.jpg', '/images/vehicles/jeep-wrangler-tn.jpg', 28475.00, 41236, 'Orange', 1),
('Ford', 'Explorer', 2020, 'The Ford Explorer is a range of SUVs manufactured by Ford.', '/images/vehicles/ford-explorer.jpg', '/images/vehicles/ford-explorer-tn.jpg', 32995.00, 12458, 'Black', 2),
('Chevrolet', 'Malibu', 2019, 'The Chevrolet Malibu is a mid-size car manufactured by Chevrolet.', '/images/vehicles/chevrolet-malibu.jpg', '/images/vehicles/chevrolet-malibu-tn.jpg', 22495.00, 32541, 'White', 3),
('Dodge', 'Ram', 2021, 'The Dodge Ram is a full-size pickup truck.', '/images/vehicles/dodge-ram.jpg', '/images/vehicles/dodge-ram-tn.jpg', 35995.00, 15896, 'Silver', 4),
('Honda', 'Odyssey', 2020, 'The Honda Odyssey is a minivan manufactured by Honda.', '/images/vehicles/honda-odyssey.jpg', '/images/vehicles/honda-odyssey-tn.jpg', 30995.00, 21548, 'Blue', 5),
('GM', 'Hummer', 2022, 'The GM Hummer is a full-size SUV with small interiors.', '/images/vehicles/gm-hummer.jpg', '/images/vehicles/gm-hummer-tn.jpg', 58995.00, 1258, 'Black', 2);

-- These are the copies of queries 4 and 6 from Task 1, as required by the assignment

-- Query 4: Delete Tony Stark record
DELETE FROM public.account 
WHERE account_email = 'tony@starkent.com';

-- Query 6: Select Sport vehicles with classification
SELECT inv_make, inv_model, classification_name
FROM public.inventory
INNER JOIN public.classification ON inventory.classification_id = classification.classification_id
WHERE classification_name = 'Sport';